APP_NAME := autorecorder

SRCS := \
    freetribe_recorder.c \
    pattern_writer.c \
    randomizer.c \
    randomizer_euclid.c \
    euclid.c \
    humanizer.c \
    rng.c \
    sync.c \
    cpu/startup.s \
    cpu/vectors.s \
    condition_stubs.c \
    euclid_nrpn_stubs.c \
    pattern_write_dummy.c \
    cpu/ft_api.c


include ../../app_common.mk
