APP_NAME := autorecorder

SRCS := \
    freetribe_recorder.c \
    freetribe_save_bundle.c \
    pattern_writer.c \
    pattern_clear.c \
    pattern_ram_map.c \
    pattern_transform.c \
    pattern_stubs.c \
    randomizer.c \
    randomizer_euclid.c \
    euclid_engine_v2.c \
    humanizer.c \
    rng.c \
    scale_engine.c \
    scale_engine_nrpn.c \
    mod_matrix.c \
    nrpn_router.c \
    live_fx.c \
    midi_out.c \
    sync.c \
    sync_live.c \
    syscalls.c \
    sysex_helper.c \
    ui_messages.c \
    condition_engine.c \
    condition_presets.c \
    euclid_nrpn_stubs.c \
    pattern_write_dummy.c \
    composer_timeline.c \
    composer_padmap.c \
    composer_policy.c \
    composer.c \
    composer_utils.c \
    composer_bridge.c \
    composer_preview.c \
    groove_engine.c \
    cpu/save_manager_stubs.c \
    cpu/startup.s \
    cpu/vectors.s \
    cpu/ft_api.c

include ../../app_common.mk
